 configuration:
     source_directory: '\\DESKTOP-ROY\rabbitmq_source'
     error_sleep_time: 5
     long_term_storage: '\\DESKTOP-ROY\rabbitmq_archive'
     allowed_file_types: ['.txt','.csv']
     log_file_name : 'send.log'
     queue: 'hello'
     host: 'localhost'
     log_file_retention : days
     


## Dynamic Yaml, per day. 
