configuration:
  source_directory: \\DESKTOP-ROY\rabbitmq_source
  error_sleep_time: 5
  long_term_storage: \\DESKTOP-ROY\rabbitmq_archive
  allowed_file_types:
    - .txt
    - .csv
  log_file_name: send.log
  queue: pikaFileTransfer
  host: localhost
  port: 5672
  log_file_retention: days
  devMode: true
credentials:
  username: rolando
  password: password
     


## Dynamic Yaml, per day. 
