configuration:
  error_sleep_time: 5
  target_directory: C:\test_dir\target\
  queue: pikaFileTransfer
  log_file_name: receive_log.log
  host: localhost
  port: 5672
  log_file_retention: days
  devMode: true
credentials:
  username: rolando
  password: password
