configuration:
  source_directory: C:\test_dir\source
  error_sleep_time: 5
  long_term_storage: C:\test_dir\archive
  allowed_file_types:
    - .txt
    - .csv
  log_file_name: send.log
  queue: pikaFileTransfer
  host: localhost
  port: 5672
  devMode: true
credentials:
  username: rolando
  password: password
     


